services:
  db:
    image: postgres:16
    container_name: mspr_pg
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: mspr_pgadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@mspr.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: mspr_airflow
    restart: unless-stopped
    depends_on:
      - db
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      PYTHONPATH: /opt/airflow/project
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: ${POSTGRES_DB:-mspr_electio}
      DB_USER: ${POSTGRES_USER:-mspr}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-mspr_password}
      TARGET_DEPT_CODES: "75,77,78,91,92,93,94,95"
      ALIGN_SOCIO_TO_ELECTION_YEARS: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./:/opt/airflow/project
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: >
      bash -c "
      airflow db init &&
      (airflow users create --username admin --password admin --firstname MSPR --lastname Admin --role Admin --email admin@example.com || true) || exit 1;
      airflow scheduler &
      exec airflow webserver --port 8080
      "

volumes:
  pg_data:
  pgadmin_data:
